// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/ConvertAnchor.lfet"
// 14.02.2025 12:20
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.anchor;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface ConvertAnchorIFace<T>
{

    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$Package=io.rulebased.group.javahelp.converter.antora.convert.anchor
    // Prolog Decision Table <----
    
    /** 
     * <b>B02: current element is ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    boolean isCurrentElementIs(ConvertAnchorIFace.CurrentElementIs arg0, T model);
    
    /** 
     * <b>B03: contains current element child elements</b>
     */
    boolean isContainsCurrentElementChildElements(T model);
    
    /** 
     * <b>B04: next child element exists</b>
     */
    boolean isNextChildElementExists(T model);
    
    /** 
     * <b>B05: current element type is ...</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    boolean isCurrentElementTypeIs(ConvertAnchorIFace.CurrentElementTypeIs arg0, T model);
    
    /** 
     * <b>B06: image is ...</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    boolean isImageIs(ConvertAnchorIFace.ImageIs arg0, T model);
    
    /** 
     * <b>B07: anchor text is empty</b>
     */
    boolean isAnchorTextIsEmpty(T model);
    
    /** 
     * <b>B08: is create list item</b>
     */
    boolean isIsCreateListItem(T model);
    
    /** 
     * <b>A01: extract anchor target</b>
     */
    void doExtractAnchorTarget(T model);
    
    /** 
     * <b>A02: set create list item</b>
     */
    void doSetCreateListItem(T model);
    
    /** 
     * <b>A03: extract anchor text</b>
     */
    void doExtractAnchorText(T model);
    
    /** 
     * <b>A04: create list item prefix</b>
     */
    void doCreateListItemPrefix(T model);
    
    /** 
     * <b>A05: create xref link</b>
     */
    void doCreateXrefLink(T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>B02: current element is ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum CurrentElementIs
    {
        /** 
         * <b>B02: current element is ...</b><br>
         * <br>
         * <b>B02/01: a - anchor</b>
         */
        $001("a", "anchor");
        
        private final String symbol;
        
        private final String title;
        
        CurrentElementIs(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>B05: current element type is ...</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    enum CurrentElementTypeIs
    {
        /** 
         * <b>B05: current element type is ...</b><br>
         * <br>
         * <b>B05/01: TN - TextNode</b>
         */
        $TN("TN", "TextNode"),
        
        /** 
         * <b>B05: current element type is ...</b><br>
         * <br>
         * <b>B05/02: EL - Element</b>
         */
        $EL("EL", "Element"),
        
        /** 
         * <b>B05: current element type is ...</b><br>
         * <br>
         * <b>B05/03: IMG - ImageNode</b>
         */
        $IMG("IMG", "ImageNode");
        
        private final String symbol;
        
        private final String title;
        
        CurrentElementTypeIs(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>B06: image is ...</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    enum ImageIs
    {
        /** 
         * <b>B06: image is ...</b><br>
         * <br>
         * <b>B06/01: butt - Button</b>
         */
        $BUTT("butt", "Button");
        
        private final String symbol;
        
        private final String title;
        
        ImageIs(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.3.0 (250206a) build in default

}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
