// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/ConvertAnchor.lfet"
// 14.02.2025 12:20
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.anchor;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class ConvertAnchorRulesEngine
{
    public <T> void execute(ConvertAnchorIFace<T> iface, T model)
    {

    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter.antora.convert.anchor
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 ) // State I - Init
            {
                if (iface.isCurrentElementIs(ConvertAnchorIFace.CurrentElementIs.$001, model) /* a - anchor */)
                {
                    if (iface.isContainsCurrentElementChildElements(model))
                    {
                        // Rule R01 ---->
                        
                        iface.doTrace("ConvertAnchor", "20250214.122008", 11, 1, model);
                        
                        iface.doExtractAnchorTarget(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R01 <----
                    }
                    else
                    {
                        // Rule R02 ---->
                        
                        iface.doTrace("ConvertAnchor", "20250214.122008", 11, 2, model);
                        
                        iface.doExtractAnchorTarget(model);
                        
                        exit = true;
                        
                        // Rule R02 <----
                    }
                }
                else // current element is ... * - other
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("ConvertAnchor", "20250214.122008", 11, 3, model);
                    
                    exit = true;
                    
                    // Rule R03 <----
                }
            }
            else // State PSE - Process sub elements
            {
                if (iface.isNextChildElementExists(model))
                {
                    if (iface.isCurrentElementTypeIs(ConvertAnchorIFace.CurrentElementTypeIs.$TN, model) /* TN - TextNode */)
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("ConvertAnchor", "20250214.122008", 11, 4, model);
                        
                        iface.doExtractAnchorText(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R04 <----
                    }
                    else if (iface.isCurrentElementTypeIs(ConvertAnchorIFace.CurrentElementTypeIs.$EL, model) /* EL - Element */)
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("ConvertAnchor", "20250214.122008", 11, 5, model);
                        
                        iface.doExtractAnchorText(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else if (iface.isCurrentElementTypeIs(ConvertAnchorIFace.CurrentElementTypeIs.$IMG, model) /* IMG - ImageNode */)
                    {
                        if (iface.isImageIs(ConvertAnchorIFace.ImageIs.$BUTT, model) /* butt - Button */)
                        {
                            // Rule R06 ---->
                            
                            iface.doTrace("ConvertAnchor", "20250214.122008", 11, 6, model);
                            
                            iface.doSetCreateListItem(model);
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            // Rule R06 <----
                        }
                        else // image is ... * - Else
                        {
                            // Rule R07 ---->
                            
                            iface.doTrace("ConvertAnchor", "20250214.122008", 11, 7, model);
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            // Rule R07 <----
                        }
                    }
                    else // current element type is ... * - other
                    {
                        // Rule R08 ---->
                        
                        iface.doTrace("ConvertAnchor", "20250214.122008", 11, 8, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R08 <----
                    }
                }
                else
                {
                    if (iface.isAnchorTextIsEmpty(model))
                    {
                        if (iface.isIsCreateListItem(model))
                        {
                            // Rule R09 ---->
                            
                            iface.doTrace("ConvertAnchor", "20250214.122008", 11, 9, model);
                            
                            iface.doCreateListItemPrefix(model);
                            
                            exit = true;
                            
                            // Rule R09 <----
                        }
                        else
                        {
                            // Rule R10 ---->
                            
                            iface.doTrace("ConvertAnchor", "20250214.122008", 11, 10, model);
                            
                            exit = true;
                            
                            // Rule R10 <----
                        }
                    }
                    else
                    {
                        // Rule R11 ---->
                        
                        iface.doTrace("ConvertAnchor", "20250214.122008", 11, 11, model);
                        
                        iface.doCreateXrefLink(model);
                        
                        exit = true;
                        
                        // Rule R11 <----
                    }
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (250206a) build in default

    }
}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
