// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-to-antora-converter/src/main/resources/ConvertAnchor.lfet"
// 03.04.2022 22:46
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.anchor;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class ConvertAnchorRulesEngine
{
    public <T> void execute(ConvertAnchorDT<T> iface, T model)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter.antora.convert.anchor
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isCurrentElementIs(ConvertAnchorDT.CurrentElementIs.$001 /* a */ , model) )
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("ConvertAnchor", "20220403.224635", 3, 1, model);
                    
                    iface.doExtractAnchor(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("ConvertAnchor", "20220403.224635", 3, 2, model);
                    
                    exit = true;
                    
                    // Rule R02 <----
                }
            }
            else
            {
                // Rule R03 ---->
                
                iface.doTrace("ConvertAnchor", "20220403.224635", 3, 3, model);
                
                exit = true;
                
                // Rule R03 <----
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

