// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/Converter.lfet"
// 11.04.2022 00:38
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class ConverterRulesEngine
{
    public <T> void execute(ConverterIFace<T> iface, T model)
    {

    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 ) // step 1 - 1
            {
                if (iface.isArgsSizeEqual_Equal0(model))
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 1, model);
                    
                    iface.doSetConfigFileName_Default(model);
                    
                    ruleGroup++;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else if (iface.isArgsSizeEqual_Equal1(model))
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 2, model);
                    
                    iface.doSetConfigFileName_Args(model);
                    
                    ruleGroup++;
                    exit = false;
                    
                    // Rule R02 <----
                }
                else // args size = > 1 - with to many arguments called
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 3, model);
                    
                    iface.doError(ConverterIFace.Error.$001, model); // MA - Two many arguments, please call Converter with path to config.yaml!
                    
                    exit = true;
                    
                    // Rule R03 <----
                }
            }
            else if ( ruleGroup == 2 ) // step 2 - 2
            {
                if (iface.isExistsConfigFile(model))
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 4, model);
                    
                    iface.doReadConfigFileAsYaml(model);
                    
                    ruleGroup++;
                    exit = false;
                    
                    // Rule R04 <----
                }
                else
                {
                    // Rule R05 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 5, model);
                    
                    iface.doError(ConverterIFace.Error.$002, model); // MCF - %s file is missing.
                    
                    exit = true;
                    
                    // Rule R05 <----
                }
            }
            else // step 3 - 3
            {
                if (iface.isInputFileTypeEqual_F(model))
                {
                    // Rule R06 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 6, model);
                    
                    iface.doSetInputFacade(ConverterIFace.SetInputFacade.$001, model); // JAR - Jar file facade
                    iface.doStartMigration(model);
                    
                    exit = true;
                    
                    // Rule R06 <----
                }
                else // input file type = D - Directory
                {
                    // Rule R07 ---->
                    
                    iface.doTrace("Converter", "20220411.003823", 7, 7, model);
                    
                    iface.doError(ConverterIFace.Error.$003, model); // NSIT - Directory as input is not supported.
                    
                    exit = true;
                    
                    // Rule R07 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (250206a) build in default

    }
}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
