// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/ExtractImages.lfet"
// 03.04.2022 23:25
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.images;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface ExtractImagesIFace<T>
{

    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$Package=io.rulebased.group.javahelp.converter.antora.convert.images
    // Prolog Decision Table <----
    
    /** 
     * <b>B02: next image element exists</b>
     */
    boolean isNextImageElementExists(T model);
    
    /** 
     * <b>B03: is image to ignore</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    boolean isIsImageToIgnore(ExtractImagesIFace.IsImageToIgnore arg0, T model);
    
    /** 
     * <b>B04: exists entry in zip file</b>
     */
    boolean isExistsEntryInZipFile(T model);
    
    /** 
     * <b>B05: Exist image directory</b>
     */
    boolean isExistImageDirectory(T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    void doError(ExtractImagesIFace.Error arg0, T model);
    
    /** 
     * <b>A02: create image directory</b>
     */
    void doCreateImageDirectory(T model);
    
    /** 
     * <b>A03: save image to image directory</b>
     */
    void doSaveImageToImageDirectory(T model);
    
    /** 
     * <b>A04: select all image elements</b>
     */
    void doSelectAllImageElements(T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>B03: is image to ignore</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum IsImageToIgnore
    {
        /** 
         * <b>B03: is image to ignore</b><br>
         * <br>
         * <b>B03/01: 001 - Images/Theme/LF/previous.gif</b>
         */
        $001("001", "Images/Theme/LF/previous.gif"),
        
        /** 
         * <b>B03: is image to ignore</b><br>
         * <br>
         * <b>B03/02: 002 - Images/Theme/LF/next_disabled2.gif</b>
         */
        $002("002", "Images/Theme/LF/next_disabled2.gif"),
        
        /** 
         * <b>B03: is image to ignore</b><br>
         * <br>
         * <b>B03/03: 003 - Images/Theme/LF/next.gif</b>
         */
        $003("003", "Images/Theme/LF/next.gif"),
        
        /** 
         * <b>B03: is image to ignore</b><br>
         * <br>
         * <b>B03/04: 004 - Images/Theme/LF/previous_disabled2.gif</b>
         */
        $004("004", "Images/Theme/LF/previous_disabled2.gif"),
        
        /** 
         * <b>B03: is image to ignore</b><br>
         * <br>
         * <b>B03/05: 005 - button.gif</b>
         */
        $005("005", "button.gif");
        
        private final String symbol;
        
        private final String title;
        
        IsImageToIgnore(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum Error
    {
        /** 
         * <b>A01: Error</b><br>
         * <br>
         * <b>A01/01: IM - Image missing</b>
         */
        $001("IM", "Image missing");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.3.0 (250206a) build in default

}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
