// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/HtmlImageExtractor.lfet"
// 03.04.2022 23:25
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.images;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class HtmlImageExtractorRulesEngine
{
    public <T> void execute(HtmlImageExtractorIFace<T> iface, T model)
    {

    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter.antora.convert.images
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 ) // State I - Initialise
            {
                // Rule R01 ---->
                
                iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 1, model);
                
                iface.doSelectAllImageElements(model);
                
                ruleGroup = 2;
                exit = false;
                
                // Rule R01 <----
            }
            else // State PI - Process Images
            {
                if (iface.isNextImageElementExists(model))
                {
                    if (iface.isIsImageToIgnore(HtmlImageExtractorIFace.IsImageToIgnore.$001, model) /* 001 - Images/Theme/LF/previous.gif */)
                    {
                        // Rule R02 ---->
                        
                        iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 2, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R02 <----
                    }
                    else if (iface.isIsImageToIgnore(HtmlImageExtractorIFace.IsImageToIgnore.$002, model) /* 002 - Images/Theme/LF/next_disabled2.gif */)
                    {
                        // Rule R03 ---->
                        
                        iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 3, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R03 <----
                    }
                    else if (iface.isIsImageToIgnore(HtmlImageExtractorIFace.IsImageToIgnore.$003, model) /* 003 - Images/Theme/LF/next.gif */)
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 4, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R04 <----
                    }
                    else if (iface.isIsImageToIgnore(HtmlImageExtractorIFace.IsImageToIgnore.$004, model) /* 004 - Images/Theme/LF/previous_disabled2.gif */)
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 5, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else if (iface.isIsImageToIgnore(HtmlImageExtractorIFace.IsImageToIgnore.$005, model) /* 005 - button.gif */)
                    {
                        // Rule R06 ---->
                        
                        iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 6, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R06 <----
                    }
                    else // is image to ignore * - Accept
                    {
                        if (iface.isExistsEntryInZipFile(model))
                        {
                            if (iface.isExistImageDirectory(model))
                            {
                                // Rule R07 ---->
                                
                                iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 7, model);
                                
                                iface.doSaveImageToImageDirectory(model);
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R07 <----
                            }
                            else
                            {
                                // Rule R08 ---->
                                
                                iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 8, model);
                                
                                iface.doCreateImageDirectory(model);
                                iface.doSaveImageToImageDirectory(model);
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R08 <----
                            }
                        }
                        else
                        {
                            // Rule R09 ---->
                            
                            iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 9, model);
                            
                            iface.doError(HtmlImageExtractorIFace.Error.$001, model); // IM - Image missing
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            // Rule R09 <----
                        }
                    }
                }
                else
                {
                    // Rule R10 ---->
                    
                    iface.doTrace("HtmlImageExtractor", "20220403.232550", 10, 10, model);
                    
                    exit = true;
                    
                    // Rule R10 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (250206a) build in default

    }
}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
