// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JavaHelpToAntoraConverter.lfet"
// 24.03.2022 14:14
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JavaHelpToAntoraConverterRulesEngine
{
    public <T> void execute(JavaHelpToAntoraConverterDT<T> iface, T model)
    {
 
    // Prolog Standard <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isExistInputJarFile(model) )
                {
                    if ( iface.isToCFileExists(model) )
                    {
                        // Rule R01 ---->
                        
                        iface.doTrace("JavaHelpToAntoraConverter", "20220324.141457", 5, 1, model);
                        
                        iface.doReadToCFile(model);
                        iface.doDeleteModulesDirectory(model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R01 <----
                    }
                    else
                    {
                        // Rule R02 ---->
                        
                        iface.doTrace("JavaHelpToAntoraConverter", "20220324.141457", 5, 2, model);
                        
                        iface.doError(JavaHelpToAntoraConverterDT.Error.$002 /* TOCFM */ , model);
                        
                        exit = true;
                        
                        // Rule R02 <----
                    }
                }
                else
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220324.141457", 5, 3, model);
                    
                    iface.doError(JavaHelpToAntoraConverterDT.Error.$001 /* IFM */ , model);
                    
                    exit = true;
                    
                    // Rule R03 <----
                }
            }
            else
            {
                if ( iface.isNextTableOfContentEntryOnLevel1Exists(model) )
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220324.141457", 5, 4, model);
                    
                    iface.doCreateModulWithNameOfTableOfContentEntry(model);
                    iface.doProcessTableOfContentEntry(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R04 <----
                }
                else
                {
                    // Rule R05 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220324.141457", 5, 5, model);
                    
                    iface.doSaveAntoraYmlToDocsDirectory(model);
                    
                    exit = true;
                    
                    // Rule R05 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

