// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JavaHelpToAntoraConverter.lfet"
// 24.03.2022 14:14
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface JavaHelpToAntoraConverterDT<T>
{
 
    // Prolog Standard <----
    
    /** 
     * <b>C02: Exist input jar file?</b>
     */
    boolean isExistInputJarFile(T model);
    
    /** 
     * <b>C03: ToC file exists?</b>
     */
    boolean isToCFileExists(T model);
    
    /** 
     * <b>C04: next table of content entry  on level 1 exists?</b>
     */
    boolean isNextTableOfContentEntryOnLevel1Exists(T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    void doError(JavaHelpToAntoraConverterDT.Error arg0, T model);
    
    /** 
     * <b>A02: create modul with name of table of content entry</b>
     */
    void doCreateModulWithNameOfTableOfContentEntry(T model);
    
    /** 
     * <b>A03: process table of content entry</b>
     */
    void doProcessTableOfContentEntry(T model);
    
    /** 
     * <b>A04: read ToC file</b>
     */
    void doReadToCFile(T model);
    
    /** 
     * <b>A05: delete modules directory</b>
     */
    void doDeleteModulesDirectory(T model);
    
    /** 
     * <b>A06: save antora.yml to docs directory</b>
     */
    void doSaveAntoraYmlToDocsDirectory(T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum Error
    {
        /** 
         * <b>A01: Error</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A01/01: IFM - Input jar file is missing</b>
         */
        $001("IFM", "Input jar file is missing"),
        
        /** 
         * <b>A01: Error</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A01/02: TOCFM - ToC file is missing</b>
         */
        $002("TOCFM", "ToC file is missing");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.2.0 (220224a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

