// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JHTAC_ExtractImages.lfet"
// 22.03.2022 17:37
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface JHTAC_ExtractImagesDT<T>
{
 
    // Prolog Standard <----
    
    /** 
     * <b>C02: next image element exists</b>
     */
    boolean isNextImageElementExists(T model);
    
    /** 
     * <b>C03: is image to ignore</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    boolean isIsImageToIgnore(JHTAC_ExtractImagesDT.IsImageToIgnore arg0, T model);
    
    /** 
     * <b>C04: exists entry in zip file</b>
     */
    boolean isExistsEntryInZipFile(T model);
    
    /** 
     * <b>C05: Exist image directory</b>
     */
    boolean isExistImageDirectory(T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    void doError(JHTAC_ExtractImagesDT.Error arg0, T model);
    
    /** 
     * <b>A02: create image directory</b>
     */
    void doCreateImageDirectory(T model);
    
    /** 
     * <b>A03: save image to image directory</b>
     */
    void doSaveImageToImageDirectory(T model);
    
    /** 
     * <b>A04: select all image elements</b>
     */
    void doSelectAllImageElements(T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>C03: is image to ignore</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum IsImageToIgnore
    {
        /** 
         * <b>C03: is image to ignore</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C03/01: 001 - Images/Theme/LF/previous.gif</b>
         */
        $001("001", "Images/Theme/LF/previous.gif"),
        
        /** 
         * <b>C03: is image to ignore</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C03/02: 002 - Images/Theme/LF/next_disabled2.gif</b>
         */
        $002("002", "Images/Theme/LF/next_disabled2.gif"),
        
        /** 
         * <b>C03: is image to ignore</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C03/03: 003 - Images/Theme/LF/next.gif</b>
         */
        $003("003", "Images/Theme/LF/next.gif"),
        
        /** 
         * <b>C03: is image to ignore</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C03/04: 004 - Images/Theme/LF/previous_disabled2.gif</b>
         */
        $004("004", "Images/Theme/LF/previous_disabled2.gif"),
        
        /** 
         * <b>C03: is image to ignore</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C03/05: 005 - button.gif</b>
         */
        $005("005", "button.gif");
        
        private final String symbol;
        
        private final String title;
        
        IsImageToIgnore(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum Error
    {
        /** 
         * <b>A01: Error</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A01/01: IM - Image missing</b>
         */
        $001("IM", "Image missing");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.2.0 (220224a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

