// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JHTAC_ToCEntry.lfet"
// 23.03.2022 01:57
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface JHTAC_ToCEntryDT<T>
{
 
    // Prolog Standard <----
    
    /** 
     * <b>C02: next nested toc entry exists</b>
     */
    boolean isNextNestedTocEntryExists(T model);
    
    /** 
     * <b>C03: Exists target file in archive</b>
     */
    boolean isExistsTargetFileInArchive(T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    void doError(JHTAC_ToCEntryDT.Error arg0, T model);
    
    /** 
     * <b>A02: process table of content entry</b>
     */
    void doProcessTableOfContentEntry(T model);
    
    /** 
     * <b>A03: convert and save html as adoc</b>
     */
    void doConvertAndSaveHtmlAsAdoc(T model);
    
    /** 
     * <b>A04: add entry to nav</b>
     */
    void doAddEntryToNav(T model);
    
    /** 
     * <b>A05: extract images</b>
     */
    void doExtractImages(T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum Error
    {
        /** 
         * <b>A01: Error</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A01/01: TFM - Target file in archive missing</b>
         */
        $001("TFM", "Target file in archive missing");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.2.0 (220224a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

