// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JHTAC_HtmlToAsciiDocConverter.lfet"
// 23.03.2022 02:51
// 
// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface JHTAC_HtmlToAsciiDocConverterDT<T>
{
 
    // Prolog Standard <----
    
    /** 
     * <b>C02: exist header title</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    boolean isExistHeaderTitle(JHTAC_HtmlToAsciiDocConverterDT.ExistHeaderTitle arg0, T model);
    
    /** 
     * <b>C03: save original file</b>
     */
    boolean isSaveOriginalFile(T model);
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    void doError(JHTAC_HtmlToAsciiDocConverterDT.Error arg0, T model);
    
    /** 
     * <b>A02: create pages directory</b>
     */
    void doCreatePagesDirectory(T model);
    
    /** 
     * <b>A03: extract header</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    void doExtractHeader(JHTAC_HtmlToAsciiDocConverterDT.ExtractHeader arg0, T model);
    
    /** 
     * <b>A04: save file in pages directory</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    void doSaveFileInPagesDirectory(JHTAC_HtmlToAsciiDocConverterDT.SaveFileInPagesDirectory arg0, T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>C02: exist header title</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum ExistHeaderTitle
    {
        /** 
         * <b>C02: exist header title</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C02/01: html head title - html head title</b>
         */
        $001("html head title", "html head title"),
        
        /** 
         * <b>C02: exist header title</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C02/02: H1 - h1</b>
         */
        $002("H1", "h1"),
        
        /** 
         * <b>C02: exist header title</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>C02/03: p.lfhtml-title-01 - p.lfhtml-title-01</b>
         */
        $003("p.lfhtml-title-01", "p.lfhtml-title-01");
        
        private final String symbol;
        
        private final String title;
        
        ExistHeaderTitle(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A01: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum Error
    {
        /** 
         * <b>A01: Error</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A01/01: HM - Header title for file '%s'  is missing</b>
         */
        $001("HM", "Header title for file '%s'  is missing");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A03: extract header</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum ExtractHeader
    {
        /** 
         * <b>A03: extract header</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A03/01: H1 - h1</b>
         */
        $001("H1", "h1"),
        
        /** 
         * <b>A03: extract header</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A03/02: html head title - html head title</b>
         */
        $002("html head title", "html head title"),
        
        /** 
         * <b>A03: extract header</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A03/03: p.lfhtml-title-01 - p.lfhtml-title-01</b>
         */
        $003("p.lfhtml-title-01", "p.lfhtml-title-01"),
        
        /** 
         * <b>A03: extract header</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A03/04: X - execute action</b>
         */
        $004("X", "execute action");
        
        private final String symbol;
        
        private final String title;
        
        ExtractHeader(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A04: save file in pages directory</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.001</b>: Symbol; Title; IncludeTagsText = $$Enum.Plain; MethodName = EnumName
     */
    enum SaveFileInPagesDirectory
    {
        /** 
         * <b>A04: save file in pages directory</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A04/01: ADOC - save converted asciidoc file</b>
         */
        $001("ADOC", "save converted asciidoc file"),
        
        /** 
         * <b>A04: save file in pages directory</b><br>
         * <br>
         * // $$Enum.Plain<br>
         * <br>
         * <b>A04/02: HTML - save original file</b>
         */
        $002("HTML", "save original file");
        
        private final String symbol;
        
        private final String title;
        
        SaveFileInPagesDirectory(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.2.0 (220224a) build in default

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

