// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JHTAC_HtmlToAsciiDocConverter.lfet"
// 23.03.2022 02:51
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JHTAC_HtmlToAsciiDocConverterRulesEngine
{
    public <T> void execute(JHTAC_HtmlToAsciiDocConverterDT<T> iface, T model)
    {
 
    // Prolog Standard <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isSaveOriginalFile(model) )
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220323.025135", 6, 1, model);
                    
                    iface.doCreatePagesDirectory(model);
                    iface.doSaveFileInPagesDirectory(JHTAC_HtmlToAsciiDocConverterDT.SaveFileInPagesDirectory.$002 /* HTML */ , model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220323.025135", 6, 2, model);
                    
                    iface.doCreatePagesDirectory(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R02 <----
                }
            }
            else
            {
                if ( iface.isExistHeaderTitle(JHTAC_HtmlToAsciiDocConverterDT.ExistHeaderTitle.$001 /* html head title */ , model) )
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220323.025135", 6, 3, model);
                    
                    iface.doExtractHeader(JHTAC_HtmlToAsciiDocConverterDT.ExtractHeader.$002 /* html head title */ , model);
                    iface.doSaveFileInPagesDirectory(JHTAC_HtmlToAsciiDocConverterDT.SaveFileInPagesDirectory.$001 /* ADOC */ , model);
                    
                    exit = true;
                    
                    // Rule R03 <----
                }
                else if ( iface.isExistHeaderTitle(JHTAC_HtmlToAsciiDocConverterDT.ExistHeaderTitle.$002 /* H1 */ , model) )
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220323.025135", 6, 4, model);
                    
                    iface.doExtractHeader(JHTAC_HtmlToAsciiDocConverterDT.ExtractHeader.$001 /* H1 */ , model);
                    iface.doSaveFileInPagesDirectory(JHTAC_HtmlToAsciiDocConverterDT.SaveFileInPagesDirectory.$001 /* ADOC */ , model);
                    
                    exit = true;
                    
                    // Rule R04 <----
                }
                else if ( iface.isExistHeaderTitle(JHTAC_HtmlToAsciiDocConverterDT.ExistHeaderTitle.$003 /* p.lfhtml-title-01 */ , model) )
                {
                    // Rule R05 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220323.025135", 6, 5, model);
                    
                    iface.doExtractHeader(JHTAC_HtmlToAsciiDocConverterDT.ExtractHeader.$003 /* p.lfhtml-title-01 */ , model);
                    iface.doSaveFileInPagesDirectory(JHTAC_HtmlToAsciiDocConverterDT.SaveFileInPagesDirectory.$001 /* ADOC */ , model);
                    
                    exit = true;
                    
                    // Rule R05 <----
                }
                else
                {
                    // Rule R06 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220323.025135", 6, 6, model);
                    
                    iface.doError(JHTAC_HtmlToAsciiDocConverterDT.Error.$001 /* HM */ , model);
                    
                    exit = true;
                    
                    // Rule R06 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

