// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JHTAC_ExtractImages.lfet"
// 22.03.2022 17:37
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JHTAC_ExtractImagesRulesEngine
{
    public <T> void execute(JHTAC_ExtractImagesDT<T> iface, T model)
    {
 
    // Prolog Standard <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                // Rule R01 ---->
                
                iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 1, model);
                
                iface.doSelectAllImageElements(model);
                
                ruleGroup = 2;
                exit = false;
                
                // Rule R01 <----
            }
            else
            {
                if ( iface.isNextImageElementExists(model) )
                {
                    if ( iface.isIsImageToIgnore(JHTAC_ExtractImagesDT.IsImageToIgnore.$001 /* 001 */ , model) )
                    {
                        // Rule R02 ---->
                        
                        iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 2, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R02 <----
                    }
                    else if ( iface.isIsImageToIgnore(JHTAC_ExtractImagesDT.IsImageToIgnore.$002 /* 002 */ , model) )
                    {
                        // Rule R03 ---->
                        
                        iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 3, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R03 <----
                    }
                    else if ( iface.isIsImageToIgnore(JHTAC_ExtractImagesDT.IsImageToIgnore.$003 /* 003 */ , model) )
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 4, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R04 <----
                    }
                    else if ( iface.isIsImageToIgnore(JHTAC_ExtractImagesDT.IsImageToIgnore.$004 /* 004 */ , model) )
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 5, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else if ( iface.isIsImageToIgnore(JHTAC_ExtractImagesDT.IsImageToIgnore.$005 /* 005 */ , model) )
                    {
                        // Rule R06 ---->
                        
                        iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 6, model);
                        
                        ruleGroup = 2;
                        exit = false;
                        
                        // Rule R06 <----
                    }
                    else
                    {
                        if ( iface.isExistsEntryInZipFile(model) )
                        {
                            if ( iface.isExistImageDirectory(model) )
                            {
                                // Rule R07 ---->
                                
                                iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 7, model);
                                
                                iface.doSaveImageToImageDirectory(model);
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R07 <----
                            }
                            else
                            {
                                // Rule R08 ---->
                                
                                iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 8, model);
                                
                                iface.doCreateImageDirectory(model);
                                iface.doSaveImageToImageDirectory(model);
                                
                                ruleGroup = 2;
                                exit = false;
                                
                                // Rule R08 <----
                            }
                        }
                        else
                        {
                            // Rule R09 ---->
                            
                            iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 9, model);
                            
                            iface.doError(JHTAC_ExtractImagesDT.Error.$001 /* IM */ , model);
                            
                            ruleGroup = 2;
                            exit = false;
                            
                            // Rule R09 <----
                        }
                    }
                }
                else
                {
                    // Rule R10 ---->
                    
                    iface.doTrace("JHTAC_ExtractImages", "20220322.173743", 10, 10, model);
                    
                    exit = true;
                    
                    // Rule R10 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

