// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-antora-converter/src/main/resources/JHTAC_ToCEntry.lfet"
// 23.03.2022 01:57
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.antora.converter;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JHTAC_ToCEntryRulesEngine
{
    public <T> void execute(JHTAC_ToCEntryDT<T> iface, T model)
    {
 
    // Prolog Standard <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isExistsTargetFileInArchive(model) )
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("JHTAC_ToCEntry", "20220323.015704", 4, 1, model);
                    
                    iface.doConvertAndSaveHtmlAsAdoc(model);
                    iface.doAddEntryToNav(model);
                    iface.doExtractImages(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("JHTAC_ToCEntry", "20220323.015704", 4, 2, model);
                    
                    iface.doError(JHTAC_ToCEntryDT.Error.$001 /* TFM */ , model);
                    
                    exit = true;
                    
                    // Rule R02 <----
                }
            }
            else
            {
                if ( iface.isNextNestedTocEntryExists(model) )
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("JHTAC_ToCEntry", "20220323.015704", 4, 3, model);
                    
                    iface.doProcessTableOfContentEntry(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R03 <----
                }
                else
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("JHTAC_ToCEntry", "20220323.015704", 4, 4, model);
                    
                    exit = true;
                    
                    // Rule R04 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

