// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/HtmlToAsciiDocConverter.lfet"
// 15.02.2025 04:54
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.html;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class HtmlToAsciiDocConverterRulesEngine
{
    public <T> void execute(HtmlToAsciiDocConverterIFace<T> iface, T model)
    {

    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter.antora.convert.html
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 ) // State INIT - Init State
            {
                if (iface.isStartElementIsDefined(model))
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 1, model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 2, model);
                    
                    iface.doSelectTextbodyElement(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R02 <----
                }
            }
            else if ( ruleGroup == 2 ) // State ECE - Evaluate current element
            {
                if (iface.isContainsStartElementChildElements(model))
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 3, model);
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R03 <----
                }
                else
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 4, model);
                    
                    exit = true;
                    
                    // Rule R04 <----
                }
            }
            else // State PCE - Process current element
            {
                if (iface.isNextElementExists(model))
                {
                    if (iface.isSkipElement(model))
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 5, model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else
                    {
                        if (iface.isCurrentElementTypeIs(HtmlToAsciiDocConverterIFace.CurrentElementTypeIs.$001, model) /* Text - TextNode */)
                        {
                            if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$001, model) /* &NBSP; - None breaking space */)
                            {
                                // Rule R06 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 6, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R06 <----
                            }
                            else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$002, model) /* EMPTY - Empty string */)
                            {
                                // Rule R07 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 7, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R07 <----
                            }
                            else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$003, model) /* BLANK - Blank string */)
                            {
                                // Rule R08 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 8, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R08 <----
                            }
                            else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$004, model) /* \n - Linebreak */)
                            {
                                // Rule R09 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 9, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R09 <----
                            }
                            else // trimmed text is equal to ... * - other
                            {
                                // Rule R10 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 10, model);
                                
                                iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$NONE, model); // NONE - extratct only text
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R10 <----
                            }
                        }
                        else if (iface.isCurrentElementTypeIs(HtmlToAsciiDocConverterIFace.CurrentElementTypeIs.$002, model) /* Elem - Element */)
                        {
                            if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$001, model) /* h1 - header with level 1 */)
                            {
                                // Rule R11 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 11, model);
                                
                                iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$EQUAL, model); // = - start with '=' multiply with current header level
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R11 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$002, model) /* h2 - header with level 2 */)
                            {
                                // Rule R12 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 12, model);
                                
                                iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$EQUAL, model); // = - start with '=' multiply with current header level
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R12 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$003, model) /* h3 - header with level 3 */)
                            {
                                // Rule R13 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 13, model);
                                
                                iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$EQUAL, model); // = - start with '=' multiply with current header level
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R13 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$004, model) /* h4 - header with level 4 */)
                            {
                                // Rule R14 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 14, model);
                                
                                iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$EQUAL, model); // = - start with '=' multiply with current header level
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R14 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$005, model) /* img - Image */)
                            {
                                // Rule R15 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 15, model);
                                
                                iface.doExtractImageSrc(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R15 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$006, model) /* b - Bold text */)
                            {
                                // Rule R16 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 16, model);
                                
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R16 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$007, model) /* i - italic text */)
                            {
                                // Rule R17 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 17, model);
                                
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R17 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$008, model) /* a - anchor */)
                            {
                                // Rule R18 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 18, model);
                                
                                iface.doExtractAnchor(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R18 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$009, model) /* font - font */)
                            {
                                if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$001, model) /* &NBSP; - None breaking space */)
                                {
                                    // Rule R19 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 19, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R19 <----
                                }
                                else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$002, model) /* EMPTY - Empty string */)
                                {
                                    // Rule R20 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 20, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R20 <----
                                }
                                else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$003, model) /* BLANK - Blank string */)
                                {
                                    // Rule R21 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 21, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R21 <----
                                }
                                else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$004, model) /* \n - Linebreak */)
                                {
                                    // Rule R22 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 22, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R22 <----
                                }
                                else // trimmed text is equal to ... * - other
                                {
                                    // Rule R23 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 23, model);
                                    
                                    iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$NONE, model); // NONE - extratct only text
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R23 <----
                                }
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$010, model) /* table - table */)
                            {
                                // Rule R24 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 24, model);
                                
                                iface.doTableHeaderEqual(HtmlToAsciiDocConverterIFace.TableHeaderEqual.$001, model); // false - false
                                iface.doAddToAdocContent(HtmlToAsciiDocConverterIFace.AddToAdocContent.$EQUALEQUALEQUAL, model); // |=== - Table
                                iface.doProcessChildElements(model);
                                iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$EQUALEQUALEQUAL, model); // |=== - Table
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R24 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$011, model) /* thead - table header */)
                            {
                                // Rule R25 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 25, model);
                                
                                iface.doTableHeaderEqual(HtmlToAsciiDocConverterIFace.TableHeaderEqual.$002, model); // true - true
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R25 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$012, model) /* tbody - table body */)
                            {
                                // Rule R26 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 26, model);
                                
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R26 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$013, model) /* tr - table row */)
                            {
                                // Rule R27 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 27, model);
                                
                                iface.doTableCountColumnsEqual(HtmlToAsciiDocConverterIFace.TableCountColumnsEqual.$001, model); // 0 - 0
                                iface.doAddToAdocContent(HtmlToAsciiDocConverterIFace.AddToAdocContent.$TR, model); // tr - table row
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R27 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$014, model) /* td - table data cell / column */)
                            {
                                // Rule R28 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 28, model);
                                
                                iface.doTableCountColumnsEqual(HtmlToAsciiDocConverterIFace.TableCountColumnsEqual.$002, model); // +1 - +1
                                iface.doAddToAdocContent(HtmlToAsciiDocConverterIFace.AddToAdocContent.$TD, model); // td - table data cell
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R28 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$015, model) /* br - line break */)
                            {
                                // Rule R29 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 29, model);
                                
                                iface.doLinebreak(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R29 <----
                            }
                            else if (iface.isCurrentElementTagnameIs(HtmlToAsciiDocConverterIFace.CurrentElementTagnameIs.$016, model) /* p - paragraph */)
                            {
                                // Rule R30 ---->
                                
                                iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 30, model);
                                
                                iface.doProcessChildElements(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R30 <----
                            }
                            else // current element tagname is ... * - other
                            {
                                if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$001, model) /* &NBSP; - None breaking space */)
                                {
                                    // Rule R31 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 31, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R31 <----
                                }
                                else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$002, model) /* EMPTY - Empty string */)
                                {
                                    // Rule R32 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 32, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R32 <----
                                }
                                else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$003, model) /* BLANK - Blank string */)
                                {
                                    // Rule R33 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 33, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R33 <----
                                }
                                else if (iface.isTrimmedTextIsEqualTo(HtmlToAsciiDocConverterIFace.TrimmedTextIsEqualTo.$004, model) /* \n - Linebreak */)
                                {
                                    // Rule R34 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 34, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R34 <----
                                }
                                else // trimmed text is equal to ... * - other
                                {
                                    // Rule R35 ---->
                                    
                                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 35, model);
                                    
                                    iface.doExtractText(HtmlToAsciiDocConverterIFace.ExtractText.$NONE, model); // NONE - extratct only text
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R35 <----
                                }
                            }
                        }
                        else // current element type is ... * - other
                        {
                            // Rule R36 ---->
                            
                            iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 36, model);
                            
                            iface.doError(HtmlToAsciiDocConverterIFace.Error.$001, model); // UT - Unknown element type
                            
                            exit = true;
                            
                            // Rule R36 <----
                        }
                    }
                }
                else
                {
                    // Rule R37 ---->
                    
                    iface.doTrace("HtmlToAsciiDocConverter", "20250215.045426", 37, 37, model);
                    
                    exit = true;
                    
                    // Rule R37 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (250206a) build in default

    }
}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
