// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-to-antora-converter/src/main/resources/JHTAC_HtmlToAsciiDocConverter.lfet"
// 23.04.2022 00:31
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.html;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JHTAC_HtmlToAsciiDocConverterRulesEngine
{
    public <T> void execute(JHTAC_HtmlToAsciiDocConverterDT<T> iface, T model)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter.antora.convert.html
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isStartElementIsDefined(model) )
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 1, model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 2, model);
                    
                    iface.doSelectTextbodyElement(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R02 <----
                }
            }
            else if ( ruleGroup == 2 )
            {
                if ( iface.isContainsCurrentElementChildElements(model) )
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 3, model);
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R03 <----
                }
                else
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 4, model);
                    
                    exit = true;
                    
                    // Rule R04 <----
                }
            }
            else
            {
                if ( iface.isNextElementExists(model) )
                {
                    if ( iface.isSkipElement(model) )
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 5, model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else
                    {
                        if ( iface.isCurrentElementTypeIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTypeIs.$001 /* T */ , model) )
                        {
                            if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$001 /* &NBSP; */ , model) )
                            {
                                // Rule R06 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 6, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R06 <----
                            }
                            else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$002 /* EMPTY */ , model) )
                            {
                                // Rule R07 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 7, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R07 <----
                            }
                            else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$003 /* BLANK */ , model) )
                            {
                                // Rule R08 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 8, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R08 <----
                            }
                            else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$004 /* \n */ , model) )
                            {
                                // Rule R09 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 9, model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R09 <----
                            }
                            else
                            {
                                // Rule R10 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 10, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$004 /* NONE */ , model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R10 <----
                            }
                        }
                        else if ( iface.isCurrentElementTypeIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTypeIs.$002 /* E */ , model) )
                        {
                            if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$001 /* h1 */ , model) )
                            {
                                // Rule R11 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 11, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$002 /* = */ , model);
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R11 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$002 /* h2 */ , model) )
                            {
                                // Rule R12 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 12, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$002 /* = */ , model);
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R12 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$003 /* h3 */ , model) )
                            {
                                // Rule R13 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 13, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$002 /* = */ , model);
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R13 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$004 /* h4 */ , model) )
                            {
                                // Rule R14 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 14, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$002 /* = */ , model);
                                iface.doIncrementCurrentHeaderLevel(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R14 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$005 /* img */ , model) )
                            {
                                // Rule R15 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 15, model);
                                
                                iface.doExtractImageSrc(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R15 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$006 /* b */ , model) )
                            {
                                // Rule R16 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 16, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$001 /* * */ , model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R16 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$007 /* i */ , model) )
                            {
                                // Rule R17 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 17, model);
                                
                                iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$003 /* _ */ , model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R17 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$008 /* a */ , model) )
                            {
                                // Rule R18 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 18, model);
                                
                                iface.doExtractAnchor(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R18 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$009 /* font */ , model) )
                            {
                                if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$001 /* &NBSP; */ , model) )
                                {
                                    // Rule R19 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 19, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R19 <----
                                }
                                else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$002 /* EMPTY */ , model) )
                                {
                                    // Rule R20 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 20, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R20 <----
                                }
                                else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$003 /* BLANK */ , model) )
                                {
                                    // Rule R21 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 21, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R21 <----
                                }
                                else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$004 /* \n */ , model) )
                                {
                                    // Rule R22 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 22, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R22 <----
                                }
                                else
                                {
                                    // Rule R23 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 23, model);
                                    
                                    iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$004 /* NONE */ , model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R23 <----
                                }
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$010 /* br */ , model) )
                            {
                                // Rule R24 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 24, model);
                                
                                iface.doLinebreak(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R24 <----
                            }
                            else if ( iface.isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs.$011 /* p */ , model) )
                            {
                                // Rule R25 ---->
                                
                                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 25, model);
                                
                                iface.doProcessElement(model);
                                
                                ruleGroup = 3;
                                exit = false;
                                
                                // Rule R25 <----
                            }
                            else
                            {
                                if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$001 /* &NBSP; */ , model) )
                                {
                                    // Rule R26 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 26, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R26 <----
                                }
                                else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$002 /* EMPTY */ , model) )
                                {
                                    // Rule R27 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 27, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R27 <----
                                }
                                else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$003 /* BLANK */ , model) )
                                {
                                    // Rule R28 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 28, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R28 <----
                                }
                                else if ( iface.isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo.$004 /* \n */ , model) )
                                {
                                    // Rule R29 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 29, model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R29 <----
                                }
                                else
                                {
                                    // Rule R30 ---->
                                    
                                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 30, model);
                                    
                                    iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$004 /* NONE */ , model);
                                    
                                    ruleGroup = 3;
                                    exit = false;
                                    
                                    // Rule R30 <----
                                }
                            }
                        }
                        else
                        {
                            // Rule R31 ---->
                            
                            iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 31, model);
                            
                            iface.doError(JHTAC_HtmlToAsciiDocConverterDT.Error.$001 /* UT */ , model);
                            
                            exit = true;
                            
                            // Rule R31 <----
                        }
                    }
                }
                else
                {
                    // Rule R32 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220423.003125", 32, 32, model);
                    
                    exit = true;
                    
                    // Rule R32 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

