// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-to-antora-converter/src/main/resources/JHTAC_HtmlToAsciiDocConverter.lfet"
// 16.04.2022 21:24
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.html;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JHTAC_HtmlToAsciiDocConverterRulesEngine
{
    public <T> void execute(JHTAC_HtmlToAsciiDocConverterDT<T> iface, T model)
    {
 
    // Prolog Standard <----

        // Prolog Decision Table ---->
        // $$Package=io.rulebased.group.javahelp.converter.antora.convert.html
        // Prolog Decision Table <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                // Rule R01 ---->
                
                iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 1, model);
                
                iface.doSelectTextbodyElement(model);
                
                ruleGroup = 2;
                exit = false;
                
                // Rule R01 <----
            }
            else if ( ruleGroup == 2 )
            {
                if ( iface.isContainsCurrentElementChildElements(model) )
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 2, model);
                    
                    ruleGroup = 3;
                    exit = false;
                    
                    // Rule R02 <----
                }
                else
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 3, model);
                    
                    exit = true;
                    
                    // Rule R03 <----
                }
            }
            else
            {
                if ( iface.isNextElementExists(model) )
                {
                    if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$001 /* h */ , model) )
                    {
                        // Rule R04 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 4, model);
                        
                        iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$002 /* = */ , model);
                        iface.doIncrementCurrentHeaderLevel(model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R04 <----
                    }
                    else if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$002 /* img */ , model) )
                    {
                        // Rule R05 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 5, model);
                        
                        iface.doExtractImageSrc(model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R05 <----
                    }
                    else if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$003 /* b */ , model) )
                    {
                        // Rule R06 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 6, model);
                        
                        iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$001 /* * */ , model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R06 <----
                    }
                    else if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$004 /* i */ , model) )
                    {
                        // Rule R07 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 7, model);
                        
                        iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$003 /* _ */ , model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R07 <----
                    }
                    else if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$005 /* a */ , model) )
                    {
                        // Rule R08 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 8, model);
                        
                        iface.doExtractAnchor(model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R08 <----
                    }
                    else if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$006 /* font */ , model) )
                    {
                        if ( iface.isTextIsNbsp(model) )
                        {
                            // Rule R09 ---->
                            
                            iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 9, model);
                            
                            ruleGroup = 3;
                            exit = false;
                            
                            // Rule R09 <----
                        }
                        else
                        {
                            // Rule R10 ---->
                            
                            iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 10, model);
                            
                            iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$004 /* NONE */ , model);
                            
                            ruleGroup = 3;
                            exit = false;
                            
                            // Rule R10 <----
                        }
                    }
                    else if ( iface.isCurrentElementIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementIs.$007 /* br */ , model) )
                    {
                        // Rule R11 ---->
                        
                        iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 11, model);
                        
                        iface.doLinebreak(model);
                        
                        ruleGroup = 3;
                        exit = false;
                        
                        // Rule R11 <----
                    }
                    else
                    {
                        if ( iface.isTextIsNbsp(model) )
                        {
                            // Rule R12 ---->
                            
                            iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 12, model);
                            
                            ruleGroup = 3;
                            exit = false;
                            
                            // Rule R12 <----
                        }
                        else
                        {
                            // Rule R13 ---->
                            
                            iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 13, model);
                            
                            iface.doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText.$004 /* NONE */ , model);
                            
                            ruleGroup = 3;
                            exit = false;
                            
                            // Rule R13 <----
                        }
                    }
                }
                else
                {
                    // Rule R14 ---->
                    
                    iface.doTrace("JHTAC_HtmlToAsciiDocConverter", "20220416.212450", 14, 14, model);
                    
                    exit = true;
                    
                    // Rule R14 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

