// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/JHTAC_HtmlToAsciiDocConverter.lfet"
// 13.02.2025 11:17
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora.convert.html;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface JHTAC_HtmlToAsciiDocConverterDT<T>
{

    // Prolog Standard <----

    // Prolog Decision Table ---->
    // $$Package=io.rulebased.group.javahelp.converter.antora.convert.html
    // Prolog Decision Table <----
    
    /** 
     * <b>B02: contains current element child elements</b>
     */
    boolean isContainsCurrentElementChildElements(T model);
    
    /** 
     * <b>B03: next element exists</b>
     */
    boolean isNextElementExists(T model);
    
    /** 
     * <b>B04: skip element</b>
     */
    boolean isSkipElement(T model);
    
    /** 
     * <b>B05: current element type is ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    boolean isCurrentElementTypeIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTypeIs arg0, T model);
    
    /** 
     * <b>B06: current element tagname is ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    boolean isCurrentElementTagnameIs(JHTAC_HtmlToAsciiDocConverterDT.CurrentElementTagnameIs arg0, T model);
    
    /** 
     * <b>B07: trimmed text is equal to ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    boolean isTrimmedTextIsEqualTo(JHTAC_HtmlToAsciiDocConverterDT.TrimmedTextIsEqualTo arg0, T model);
    
    /** 
     * <b>B08: start element is defined</b>
     */
    boolean isStartElementIsDefined(T model);
    
    /** 
     * <b>A01: table header=</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    void doTableHeaderEqual(JHTAC_HtmlToAsciiDocConverterDT.TableHeaderEqual arg0, T model);
    
    /** 
     * <b>A02: table count columns=</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    void doTableCountColumnsEqual(JHTAC_HtmlToAsciiDocConverterDT.TableCountColumnsEqual arg0, T model);
    
    /** 
     * <b>A03: extract image src</b>
     */
    void doExtractImageSrc(T model);
    
    /** 
     * <b>A04: select textbody element</b>
     */
    void doSelectTextbodyElement(T model);
    
    /** 
     * <b>A05: extract anchor</b>
     */
    void doExtractAnchor(T model);
    
    /** 
     * <b>A06: add to adoc content</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    void doAddToAdocContent(JHTAC_HtmlToAsciiDocConverterDT.AddToAdocContent arg0, T model);
    
    /** 
     * <b>A07: process element</b>
     */
    void doProcessElement(T model);
    
    /** 
     * <b>A08: extract text</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    void doExtractText(JHTAC_HtmlToAsciiDocConverterDT.ExtractText arg0, T model);
    
    /** 
     * <b>A09: increment current header level</b>
     */
    void doIncrementCurrentHeaderLevel(T model);
    
    /** 
     * <b>A10: linebreak</b>
     */
    void doLinebreak(T model);
    
    /** 
     * <b>A11: error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    void doError(JHTAC_HtmlToAsciiDocConverterDT.Error arg0, T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>B05: current element type is ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum CurrentElementTypeIs
    {
        /** 
         * <b>B05: current element type is ...</b><br>
         * <br>
         * <b>B05/01: Text - TextNode</b>
         */
        $001("Text", "TextNode"),
        
        /** 
         * <b>B05: current element type is ...</b><br>
         * <br>
         * <b>B05/02: Elem - Element</b>
         */
        $002("Elem", "Element");
        
        private final String symbol;
        
        private final String title;
        
        CurrentElementTypeIs(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>B06: current element tagname is ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum CurrentElementTagnameIs
    {
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/01: h1 - header with level 1</b>
         */
        $001("h1", "header with level 1"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/02: h2 - header with level 2</b>
         */
        $002("h2", "header with level 2"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/03: h3 - header with level 3</b>
         */
        $003("h3", "header with level 3"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/04: h4 - header with level 4</b>
         */
        $004("h4", "header with level 4"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/05: img - Image</b>
         */
        $005("img", "Image"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/06: b - Bold text</b>
         */
        $006("b", "Bold text"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/07: i - italic text</b>
         */
        $007("i", "italic text"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/08: a - anchor</b>
         */
        $008("a", "anchor"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/09: font - font</b>
         */
        $009("font", "font"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/10: table - table</b>
         */
        $010("table", "table"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/11: thead - table header</b>
         */
        $011("thead", "table header"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/12: tbody - table body</b>
         */
        $012("tbody", "table body"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/13: tr - table row</b>
         */
        $013("tr", "table row"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/14: td - table data cell / column</b>
         */
        $014("td", "table data cell / column"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/15: br - line break</b>
         */
        $015("br", "line break"),
        
        /** 
         * <b>B06: current element tagname is ...</b><br>
         * <br>
         * <b>B06/16: p - paragraph</b>
         */
        $016("p", "paragraph");
        
        private final String symbol;
        
        private final String title;
        
        CurrentElementTagnameIs(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>B07: trimmed text is equal to ...</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum TrimmedTextIsEqualTo
    {
        /** 
         * <b>B07: trimmed text is equal to ...</b><br>
         * <br>
         * <b>B07/01: &amp;NBSP; - None breaking space</b>
         */
        $001("&NBSP;", "None breaking space"),
        
        /** 
         * <b>B07: trimmed text is equal to ...</b><br>
         * <br>
         * <b>B07/02: EMPTY - Empty string</b>
         */
        $002("EMPTY", "Empty string"),
        
        /** 
         * <b>B07: trimmed text is equal to ...</b><br>
         * <br>
         * <b>B07/03: BLANK - Blank string</b>
         */
        $003("BLANK", "Blank string"),
        
        /** 
         * <b>B07: trimmed text is equal to ...</b><br>
         * <br>
         * <b>B07/04: \n - Linebreak</b>
         */
        $004("\\n", "Linebreak");
        
        private final String symbol;
        
        private final String title;
        
        TrimmedTextIsEqualTo(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A01: table header=</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum TableHeaderEqual
    {
        /** 
         * <b>A01: table header=</b><br>
         * <br>
         * <b>A01/01: false - false</b>
         */
        $001("false", "false"),
        
        /** 
         * <b>A01: table header=</b><br>
         * <br>
         * <b>A01/02: true - true</b>
         */
        $002("true", "true");
        
        private final String symbol;
        
        private final String title;
        
        TableHeaderEqual(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A02: table count columns=</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum TableCountColumnsEqual
    {
        /** 
         * <b>A02: table count columns=</b><br>
         * <br>
         * <b>A02/01: 0 - 0</b>
         */
        $001("0", "0"),
        
        /** 
         * <b>A02: table count columns=</b><br>
         * <br>
         * <b>A02/02: +1 - +1</b>
         */
        $002("+1", "+1");
        
        private final String symbol;
        
        private final String title;
        
        TableCountColumnsEqual(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A06: add to adoc content</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    enum AddToAdocContent
    {
        /** 
         * <b>A06: add to adoc content</b><br>
         * <br>
         * <b>A06/01: |=== - Table</b>
         */
        $EQUALEQUALEQUAL("|===", "Table"),
        
        /** 
         * <b>A06: add to adoc content</b><br>
         * <br>
         * <b>A06/02: tr - table row</b>
         */
        $TR("tr", "table row"),
        
        /** 
         * <b>A06: add to adoc content</b><br>
         * <br>
         * <b>A06/03: td - table data cell</b>
         */
        $TD("td", "table data cell");
        
        private final String symbol;
        
        private final String title;
        
        AddToAdocContent(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A08: extract text</b><br>
     * <br>
     * // $$Enum.Symbol<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.2</b>: Symbol=true; Title=true; MethodName=EnumName; EnumValueName=Symbol, UpperCase, Prefix$; IncludeTagsText=$$Enum.Symbol
     */
    enum ExtractText
    {
        /** 
         * <b>A08: extract text</b><br>
         * <br>
         * <b>A08/01: * - surround with *</b>
         */
        $001("*", "surround with *"),
        
        /** 
         * <b>A08: extract text</b><br>
         * <br>
         * <b>A08/02: = - start with '=' multiply with current header level</b>
         */
        $EQUAL("=", "start with '=' multiply with current header level"),
        
        /** 
         * <b>A08: extract text</b><br>
         * <br>
         * <b>A08/03: _ - surround with _</b>
         */
        $_("_", "surround with _"),
        
        /** 
         * <b>A08: extract text</b><br>
         * <br>
         * <b>A08/04: NONE - extratct only text</b>
         */
        $NONE("NONE", "extratct only text"),
        
        /** 
         * <b>A08: extract text</b><br>
         * <br>
         * <b>A08/05: |=== - Table</b>
         */
        $EQUALEQUALEQUAL("|===", "Table");
        
        private final String symbol;
        
        private final String title;
        
        ExtractText(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }
    
    /** 
     * <b>A11: error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum Error
    {
        /** 
         * <b>A11: error</b><br>
         * <br>
         * <b>A11/01: UT - Unknown element type</b>
         */
        $001("UT", "Unknown element type");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.3.0 (250206a) build in default

}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
