// *** WARNING: DO NOT MODIFY *** This is a generated Java source code!
//
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/JavaHelpToAntoraConverter.lfet"
// 13.02.2025 15:43
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JavaHelpToAntoraConverterRulesEngine
{
    public <T> void execute(JavaHelpToAntoraConverterDT<T> iface, T model)
    {

    // Prolog Standard <----

        int ruleGroup = 1;
        boolean exit = false;

        while ( !exit )
        {
            exit = true;

            if ( ruleGroup == 1 ) // Step ImpToC - Import TOC-File from ZIP-/JAR-File
            {
                if (iface.isExistsTableOfContentFile(model))
                {
                    // Rule R01 ---->

                    iface.doTrace("JavaHelpToAntoraConverter", "20250213.154336", 6, 1, model);

                    iface.doReadToCFile(model);
                    iface.doDeleteModulesDirectory(model);

                    ruleGroup = 2;
                    exit = false;

                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->

                    iface.doTrace("JavaHelpToAntoraConverter", "20250213.154336", 6, 2, model);

                    iface.doError(JavaHelpToAntoraConverterDT.Error.$001, model); // TOCFM - ToC file is missing

                    exit = true;

                    // Rule R02 <----
                }
            }
            else if ( ruleGroup == 2 ) // Step CrMaps - Create file/path mappings JavaHelp <-> Antora
            {
                if (iface.isNextTableOfContentEntryOnLevel1Exists(model))
                {
                    // Rule R03 ---->

                    iface.doTrace("JavaHelpToAntoraConverter", "20250213.154336", 6, 3, model);

                    iface.doCreateAllMappingsForTocEntry(model);

                    ruleGroup = 2;
                    exit = false;

                    // Rule R03 <----
                }
                else
                {
                    // Rule R04 ---->

                    iface.doTrace("JavaHelpToAntoraConverter", "20250213.154336", 6, 4, model);

                    iface.doResetTocIterator(model);

                    ruleGroup = 3;
                    exit = false;

                    // Rule R04 <----
                }
            }
            else // Step Convert - Convert all entries from TOC-File to Antora
            {
                if (iface.isNextTableOfContentEntryOnLevel1Exists(model))
                {
                    // Rule R05 ---->

                    iface.doTrace("JavaHelpToAntoraConverter", "20250213.154336", 6, 5, model);

                    iface.doCreateModulWithNameOfTableOfContentEntry(model);
                    iface.doProcessTableOfContentEntry(model);
                    iface.doAddModuleEntryToAnoraYmlNav(model);

                    ruleGroup = 3;
                    exit = false;

                    // Rule R05 <----
                }
                else
                {
                    // Rule R06 ---->

                    iface.doTrace("JavaHelpToAntoraConverter", "20250213.154336", 6, 6, model);

                    iface.doSaveAntoraYmlToDocsDirectory(model);

                    exit = true;

                    // Rule R06 <----
                }
            }

        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (250206a) build in default

    }
}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
