// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/javahelp-to-antora-converter/src/main/resources/JavaHelpToAntoraConverter.lfet"
// 14.02.2025 16:25
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.ini not found
// used LF-ET 2.3.0 (250206a) build in default

package io.rulebased.group.javahelp.converter.antora;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("UnnecessaryFullyQualifiedName")
interface JavaHelpToAntoraConverterIFace<T>
{

    // Prolog Standard <----
    
    /** 
     * <b>B02: toc file exists?</b>
     */
    boolean isTocFileExists(T model);
    
    /** 
     * <b>B03: next level 1 toc entry exists?</b>
     */
    boolean isNextLevel1TocEntryExists(T model);
    
    /** 
     * <b>A01: import toc file</b>
     */
    void doImportTocFile(T model);
    
    /** 
     * <b>A02: delete modules directory</b>
     */
    void doDeleteModulesDirectory(T model);
    
    /** 
     * <b>A03: create all mappings for toc entry</b>
     */
    void doCreateAllMappingsForTocEntry(T model);
    
    /** 
     * <b>A04: reset toc iterator</b>
     */
    void doResetTocIterator(T model);
    
    /** 
     * <b>A05: create modul with name of toc entry</b>
     */
    void doCreateModulWithNameOfTocEntry(T model);
    
    /** 
     * <b>A06: process toc entry</b>
     */
    void doProcessTocEntry(T model);
    
    /** 
     * <b>A07: add module entry to antora.yml nav section</b>
     */
    void doAddModuleEntryToAntoraYmlNavSection(T model);
    
    /** 
     * <b>A08: save antora.yml to docs directory</b>
     */
    void doSaveAntoraYmlToDocsDirectory(T model);
    
    /** 
     * <b>A09: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    void doError(JavaHelpToAntoraConverterIFace.Error arg0, T model);
    
    void doTrace(java.lang.String dtName, java.lang.String version, int rules, int rule, T model);
    
    /** 
     * <b>A09: Error</b><br>
     * <br>
     * // $$Enum.Plain<br>
     * <br>
     * The enum generation has been triggered in project.ini by:<br>
     * - <b>ide.Java.InterfaceEnum.1</b>: Symbol=true; Title=true; MethodName=EnumName; IncludeTagsText=$$Enum.Plain
     */
    enum Error
    {
        /** 
         * <b>A09: Error</b><br>
         * <br>
         * <b>A09/01: TOCFM - ToC file is missing</b>
         */
        $001("TOCFM", "ToC file is missing");
        
        private final String symbol;
        
        private final String title;
        
        Error(String symbol, String title)
        {
            this.symbol = symbol;
            this.title = title;
        }
        
        public String getSymbol()
        {
            return symbol;
        }
        
        public String getTitle()
        {
            return title;
        }
    }

    // Epilog Standard ---->
    // profile LFET.Java.Epilog.Standard.Interface.ini not found
    // used LF-ET 2.3.0 (250206a) build in default

}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (250206a), https://www.lohrfink.de/lfet
