// *** WARNING: DO NOT MODIFY *** This is a generated Java source code! 
// 
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet
// From decision table
// "/opt/data/github/rulebased-group/javahelp-to-antora-converter/src/main/resources/JavaHelpToAntoraConverter.lfet"
// 11.04.2022 23:01
// 

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.2.0 (220224a) build in default

package io.rulebased.group.javahelp.converter.antora;

import javax.annotation.Generated;

@Generated("LF-ET")
@SuppressWarnings("ConstantConditions")
class JavaHelpToAntoraConverterRulesEngine
{
    public <T> void execute(JavaHelpToAntoraConverterDT<T> iface, T model)
    {
 
    // Prolog Standard <----
        
        int ruleGroup = 1;
        boolean exit = false;
        
        while ( !exit )
        {
            exit = true;
            
            if ( ruleGroup == 1 )
            {
                if ( iface.isExistsTableOfContentFile(model) )
                {
                    // Rule R01 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220411.230129", 4, 1, model);
                    
                    iface.doReadToCFile(model);
                    iface.doDeleteModulesDirectory(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R01 <----
                }
                else
                {
                    // Rule R02 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220411.230129", 4, 2, model);
                    
                    iface.doError(JavaHelpToAntoraConverterDT.Error.$001 /* TOCFM */ , model);
                    
                    exit = true;
                    
                    // Rule R02 <----
                }
            }
            else
            {
                if ( iface.isNextTableOfContentEntryOnLevel1Exists(model) )
                {
                    // Rule R03 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220411.230129", 4, 3, model);
                    
                    iface.doCreateModulWithNameOfTableOfContentEntry(model);
                    iface.doProcessTableOfContentEntry(model);
                    iface.doAddModuleEntryToNav(model);
                    
                    ruleGroup = 2;
                    exit = false;
                    
                    // Rule R03 <----
                }
                else
                {
                    // Rule R04 ---->
                    
                    iface.doTrace("JavaHelpToAntoraConverter", "20220411.230129", 4, 4, model);
                    
                    iface.doSaveAntoraYmlToDocsDirectory(model);
                    
                    exit = true;
                    
                    // Rule R04 <----
                }
            }
        
        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.2.0 (220224a) build in default

    }

}
 
// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.2.0 (220224a), https://www.lohrfink.de/lfet

