name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install jdk
        uses: actions/setup-java@v2
        with:
          java-version: 11
          vendor: openjdk

      - name: Run tests
        run: |
          mvn test

      - name: Create executable jar
        run: |
          mvn package -DskipTests
